name: guam_community_client
description: We connect developers.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.5

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.3
  cupertino_icons: ^1.0.5
  hexcolor: ^2.0.7
  modal_bottom_sheet: ^2.0.1
  flutter_form_builder: ^7.3.1
  intl: ^0.17.0
  bot_toast: ^4.0.3
  dotted_border: ^2.0.0+2
  url_launcher: ^6.1.5
  flutter_secure_storage: ^6.0.0
  flutter_portal: ^0.4.0
  flutter_mentions: ^2.0.1
  jiffy: ^5.0.0
  flutter_linkify: ^5.0.2
  path_provider: ^2.0.11

  # Image
  flutter_svg: ^1.0.3
  transparent_image: ^2.0.0
  image_picker: ^0.8.5+3
  carousel_slider: ^4.1.1

  # FlutterFire
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.4
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.4.7
  firebase_messaging: ^13.0.1

  # Social Login Dependency
  kakao_flutter_sdk: ^1.2.2
  dio: ^4.0.6
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  platform: ^3.1.0
  package_info: ^2.0.2
  google_sign_in: ^5.4.1
  flutter_dotenv: ^5.0.2

  # Share & Dynamic links
  firebase_dynamic_links: ^4.3.6
  share_plus: ^4.1.0
  sign_in_with_apple: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/gifs/
    - assets/backgrounds/
    - assets/backgrounds/splash/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SpoqaHanSansNeoMedium
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
          weight: 400
    - family: SpoqaHanSansNeoRegular
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
